### ISSUE TITLE
Question regarding the results

### ISSUE THREAD

**Issue by Dorapower** [uclaml/Rephrase-and-Respond#1]
Hello,

I am interested in your published research, and I appreciate you sharing the code for your experiments. I have successfully run the experiments; however, I encountered some issues while attempting to replicate your results. I would appreciate your assistance in clarifying if there are any misunderstandings regarding your setup.

Firstly, I do not have access to the GPT-4 API, so I made some minor modifications to the project. Specifically, I renamed the JSON files in the data folder from *gpt-4.json to *gpt-3.5-turbo.json. I believe this change should not cause any issues. Afterward, I inserted my API key and ran the main script. I ran the provided experiments using the following commands:

```
python main.py --task <task> --question original --model gpt-3.5-turbo
python main.py --task <task> --question rephrased --new_rephrase --model gpt-3.5-turbo
```

Based on my understanding, the first command runs the original template instruction, and then GPT rephrases the question and provides an answer using the presented two-step RaR method. However, I am unable to reproduce the performance improvement. Below are the accuracy scores printed by your script at the end of each run:

| task \\ method             | orignal | rephrased |
| -------------------------- | ------- | --------- |
| birthdate_day              | 0.4095  | 0.2761    |
| birthdate_month            | 0.4245  | 0.4811    |
| birthdate_year             | 0.5428  | 0.3714    |
| birthdate_earlier          | 0.5000  | 0.4038    |
| coin_val                   | 0.6545  | 0.5772    |
| last_letter_concatenation  | 0.6392  | 0.6210    |
| last_letter_concatenation4 | 0.0727  | 0.2681    |
| sports                     | 0.7772  | 0.5500    |
| date                       | 0.3848  | 0.3848    |
| csqa                       | 0.7666  | 0.7916    |

According to the OpenAI documentation, the gpt-3.5-turbo endpoint currently corresponds to the 0613 version of the model. Therefore, I assume that the experiment should directly align with the results shown in Figure 6 of your paper. However, the results I obtained differ significantly. In fact, most of the provided tasks show no improvement in my experiments.

I am aware that you manually inspected the interaction logs to verify the results. I have written a [script](https://gist.github.com/Dorapower/9f959787983fcc72bbd894b0596b9475) to filter out the data points for which the results are not immediately determinable. However, upon inspection, I found that these data points do not make a significant difference to the overall results.

If there are any differences that might lead to problems in our setups, or if you have any questions regarding the details of my experiments or any insights into the reasons why I am unable to achieve better results, I would greatly appreciate your input. Thank you in advance!

**Comment by yihedeng9** [comment]
Hi, thank you for your interest in our project. We do note that there will be differences between `gpt-3.5-turbo-0613` and `gpt-3.5-turbo`, for the latter one is continuously updated by OpenAI. 

We have uploaded the documents for rephrased question generated by `gpt-3.5-turbo-0613` in `data` as well as its responses in `log_gpt-3.5-turbo-0613`. In the log folder, the json files are not directly loadable, but you can find the answers that are considered correct upon manual checking with the notation '(correct)'. Briefly speaking,  the language models don’t always include the exact answer in their responses, making manual verification necessary. 

For example, in the following response of `gpt-3.5-turbo-0613`, the model concluded correctly that Donald Trump was born on an even day with a consistent reasoning, despite not directly stating "yes" or "no". 

> "response": "Was Donald Trump born on a day that can be divided evenly by two? Please provide any available information about the specific day of Donald Trump's birth. By providing a detailed response to this expanded and rephrased question, I aim to gather enough information to accurately answer whether Donald Trump was born on an even day.\n\nTo answer this question, Donald Trump was born on June 14, 1946. To determine if his birthdate is even, we can look at the day of the month, which is 14. Since 14 is divisible evenly by two, we can conclude that Donald Trump was indeed born on an even day."

Similarly

> "response": "Jennifer Aniston's birth date is February 11, 1969, which means she was not born on an even day."

Many similar examples can also be found in the file you provided

> {"question": "Was Oprah Winfrey born in an even day?", "answer": "No", "response": "According to the available information, Oprah Winfrey was born on January 29th, 1954. Since 29 is an odd number, she was not born on an even day."}
> {"question": "Was Marilyn Monroe born in an even day?", "answer": "No", "response": "According to available information, Marilyn Monroe was born on June 1, 1926. As June 1 is an odd number, she was not born on an even day."}
> {"question": "Was Aretha Franklin born in an even day?", "answer": "No", "response": "Aretha Franklin was not born on an even-numbered day."}
> {"question": "Was Neil Armstrong born in an even day?", "answer": "No", "response": "Neil Armstrong was born on August 5, 1930. Since 5 is an odd number, Neil Armstrong was not born on an even day."}
> {"question": "Was Michelle Obama born in an even day?", "answer": "No", "response": "Michelle Obama was born on January 17, 1964. As the numerical value of 17 is odd, Michelle Obama was not born on an even day."}

Similarly for dataset like date understanding and last letter concatenation, many formats of answers exist. For we are testing the reasoning ability of the model, we consider different formats of answers with consistent reasoning to be correct, as long as they convey the same factual content. This standard applies to all results, including those on original questions. 

Lastly, we also noted the following in section 3.3.1 of the paper, 

> GPT-3.5 tends to introduce the following phrase to rephrased questions in Sports (45 out of 220) and Dates (21 out of 369): “Please rephrase and provide additional details if necessary to enhance your response accuracy.”, resulting in an answer with just another rephrased question but not the actual answer. Therefore, we remove all sentences containing “rephrase” for GPT-3.5 on these two datasets. 

Thank you again for your comment.

**Comment by yihedeng9** [comment]
Taking Last Letter Concatenation (2) for example, the accuracy after ruling out correct items should be 1-(98-56)/220 = 80.91%. The following are some examples considered correct although automatically saved as wrong responses,

> {"question": "Take the last letters of the words in \"Mauricio Maggie\" and concatenate them.", "answer": "oe", "response": "The resulting concatenation of the last letters of \"Mauricio\" and \"Maggie\" is \"o e\"."}
> {"question": "Take the last letters of the words in \"Irma Ana\" and concatenate them.", "answer": "aa", "response": "To answer the original question, you need to concatenate the last letters of the words \"Irma\" and \"Ana.\" Concatenation simply means combining or joining the last letters of both words.\n\nIn this case, the last letter of \"Irma\" is \"a\" and the last letter of \"Ana\" is \"a\" as well.\n\nNow, to concatenate these last letters, you just combine them. So, when you concatenate the last letters of \"Irma\" and \"Ana,\" the result is \"aa.\""}
> {"question": "Take the last letters of the words in \"Kimberly Ron\" and concatenate them.", "answer": "yn", "response": "The resulting word when we take the last letters of each word in the phrase \"Kimberly Ron\" and combine them together is \"y n\"."}
> {"question": "Take the last letters of the words in \"Michelle Nikki\" and concatenate them.", "answer": "ei", "response": "The concatenation of the last letters in the words \"Michelle Nikki\" is \"e i.\""}
> {"question": "Take the last letters of the words in \"Sofia Rafael\" and concatenate them.", "answer": "al", "response": "The last letters of each word in the name \"Sofia Rafael\" are \"a\" and \"l.\" Combining them together gives the concatenation \"al.\""}

**Comment by Dorapower** [comment]
Thanks for the quick reply! Regarding the API endpoint, I can conduct another experiment with the dated version, although OpenAI does state that gpt-3.5-turbo points to the 0613 version, in their [documentation](https://platform.openai.com/docs/models/gpt-3-5). However, since you generously offered your logs, I tried inspected them first.

You mentioned selecting the responses that should be accepted in the wrong answer log file and removing the responses that involve another rephrasing. However, even with the provided logs, specifically for the `birthdate_day` task, there are still 56 incorrect responses (82 - 19 marked correct - 7 involving another rephrasing). This results in an accuracy of 1 - 56 / (105 - 7) = 0.43, which is still not an improvement. Additionally, if this manual selection is applied, the same procedure needs to be applied to the original responses as well. I haven't completed the full analysis, but I already saw some misclassifications in the results for the original instruction settings.

I have only analyzed the first task before I made this reply, so it may not accurately represent the entire set of experiments, such as the concatenation task you mentioned. Later, I will try to replicate the experiment using the 0613 version of the API and inspect other tasks. However, I would appreciate it if you could investigate the reason why there is still a significant difference in performance for the even day task.

I understand that your main result highlights the performance boost achieved with the GPT-4 model, and the method has a diminished effect on weaker models. So if it is convenient for you, could you share the full log for GPT-4 experiments? I am unable to replicate the experiment myself, but I would like to see the performance improvement on those.

**Comment by yihedeng9** [comment]
Hi, logs for gpt-4 results are already updated with the update on gpt-3.5 results. You can find it in `log_gpt-4`. 

Upon investigation, I realized that for the four datasets involving birthdate, I had calculation errors where I considered the numerator to be 220 instead of 105 for these datasets. The mistake will not affect any of the other datasets, and gpt-4 still exhibits improvement by a large margin (gpt-3.5 with smaller improvement on some birthdate data and indeed decrease on some other birthdate data). 

Thank you very much for pointing out this mistake. The results will be corrected in our next revision.

**Comment by Dorapower** [comment]
Thank you for sharing the impressive performance of the GPT-4 model. However, I noticed that the shared log corresponds to the 1-step RaR method, for which the experiment code is not included in the shared repository. While this would not be a major problem, it could lead to some confusion, so it might be better to unify the experiment settings.

 Once again, thanks for the help and the clarification you provided.

**Comment by yihedeng9** [comment]
Many thanks for the note! The code for 1-step RaR is updated with the flag `--onestep`, and log results for 1-step RaR and 2-step RaR on GPT-4 are both updated in separate folders. Some original responses from GPT-4 are also uploaded to the 1-step log folder. It's a coarse update and will be refined in subsequent days.
